// <auto-generated />
namespace MLM.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class TopAchivers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TopAchivers));
        
        string IMigrationMetadata.Id
        {
            get { return "201507040933140_TopAchivers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
